package ma.estore.models;
// Generated 22 avr. 2020 11:12:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name="COMMENTAIRE"
    ,schema="ESTORE"
)
public class Commentaire  implements java.io.Serializable {


     private long idcomm;
     private Produit produit;
     private Commande commande;
     private String commentaire;
     private Date datePub;

    public Commentaire() {
    }

	
    public Commentaire(long idcomm) {
        this.idcomm = idcomm;
    }
    public Commentaire(long idcomm, Produit produit, Commande commande, String commentaire, Date datePub) {
       this.idcomm = idcomm;
       this.produit = produit;
       this.commande = commande;
       this.commentaire = commentaire;
       this.datePub = datePub;
    }
   
     @Id 

    
    @Column(name="IDCOMM", unique=true, nullable=false, precision=10, scale=0)
    public long getIdcomm() {
        return this.idcomm;
    }
    
    public void setIdcomm(long idcomm) {
        this.idcomm = idcomm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDP")
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCMD")
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    
    @Column(name="COMMENTAIRE")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_PUB", length=7)
    public Date getDatePub() {
        return this.datePub;
    }
    
    public void setDatePub(Date datePub) {
        this.datePub = datePub;
    }




}


