package ma.estore.models;
// Generated 22 avr. 2020 11:12:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name="COMPTE"
    ,schema="ESTORE"
)
public class Compte  implements java.io.Serializable {


     private String login;
     private String mdp;
     private String role;
     private String question;
     private String reponse;
     private Date dateCreation;
     private Set<Client> clients = new HashSet<Client>(0);

    public Compte() {
    }

	
    public Compte(String login) {
        this.login = login;
    }
    public Compte(String login, String mdp, String role, String question, String reponse, Date dateCreation, Set<Client> clients) {
       this.login = login;
       this.mdp = mdp;
       this.role = role;
       this.question = question;
       this.reponse = reponse;
       this.dateCreation = dateCreation;
       this.clients = clients;
    }
   
     @Id 

    
    @Column(name="LOGIN", unique=true, nullable=false, length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="MDP", length=50)
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    
    @Column(name="ROLE", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="QUESTION")
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="REPONSE")
    public String getReponse() {
        return this.reponse;
    }
    
    public void setReponse(String reponse) {
        this.reponse = reponse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION", length=7)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compte")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


