package ma.estore.models;
// Generated 22 avr. 2020 11:12:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name="PROMOTION"
    ,schema="ESTORE"
)

@SequenceGenerator(name = "seq_promo",sequenceName = "seq_promo")
public class Promotion  implements java.io.Serializable {


     private int idprom;
     private Produit produit;
     private Date dateDebut;
     private Date dateFin;
     private int taux;

    public Promotion() {
    }

	
    public Promotion(int idprom) {
        this.idprom = idprom;
    }
    public Promotion(int idprom, Produit produit, Date dateDebut, Date dateFin, int taux) {
       this.idprom = idprom;
       this.produit = produit;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.taux = taux;
    }
   
     @Id 

    @GeneratedValue(generator = "seq_promo",strategy = GenerationType.SEQUENCE)
    @Column(name="IDPROM", unique=true, nullable=false, precision=8, scale=0)
    public int getIdprom() {
        return this.idprom;
    }
    
    public void setIdprom(int idprom) {
        this.idprom = idprom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDP")
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEBUT", length=7)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FIN", length=7)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="TAUX", precision=2, scale=0)
    public int getTaux() {
        return this.taux;
    }
    
    public void setTaux(int taux) {
        this.taux = taux;
    }




}


