package ma.estore.models;
// Generated 22 avr. 2020 11:12:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name="WISHLIST"
    ,schema="ESTORE"
)
public class Wishlist  implements java.io.Serializable {


     private long idw;
     private Client client;
     private String libelle;
     private Set<Produit> produits = new HashSet<Produit>(0);

    public Wishlist() {
    }

	
    public Wishlist(long idw) {
        this.idw = idw;
    }
    public Wishlist(long idw, Client client, String libelle, Set<Produit> produits) {
       this.idw = idw;
       this.client = client;
       this.libelle = libelle;
       this.produits = produits;
    }
   
     @Id 

    
    @Column(name="IDW", unique=true, nullable=false, precision=10, scale=0)
    public long getIdw() {
        return this.idw;
    }
    
    public void setIdw(long idw) {
        this.idw = idw;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDC")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="LIBELLE", length=30)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ITEMWISHLIST", schema="ESTORE", joinColumns = { 
        @JoinColumn(name="IDW", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDP", nullable=false, updatable=false) })
    public Set<Produit> getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set<Produit> produits) {
        this.produits = produits;
    }




}


